Repository Runnect/Runnect-Android, pull requests merged in 2023-10, with the labels that each got.

#255 [DEL] 출발지 검색 / 불필요한 onTextChanged 관련 코드 제거
  app/src/main/java/com/runnect/runnect/presentation/search/SearchActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/search/SearchViewModel.kt
  app/src/main/res/layout/activity_search.xml
Labels: 우남 🐼, DEL ❌

#243 [FEAT] 코스 그리기 / 출발지 설정 구현 (현위치, 사용자 지정)
  app/src/debug/res/drawable/draw_require_coure_name_border.xml
  app/src/debug/res/drawable/ic_current_location.xml
  app/src/debug/res/drawable/ic_custom_location.xml
  app/src/debug/res/drawable/ic_drag.xml
  app/src/debug/res/drawable/ic_info_window.xml
  app/src/main/java/com/runnect/runnect/data/dto/LocationData.kt
  app/src/main/java/com/runnect/runnect/data/dto/SearchResultEntity.kt
  app/src/main/java/com/runnect/runnect/data/dto/tmap/geocoding/ResponseReverseGeocodingDto.kt
  app/src/main/java/com/runnect/runnect/data/repository/DepartureSearchRepositoryImpl.kt
  app/src/main/java/com/runnect/runnect/data/repository/ReverseGeocodingRepositoryImpl.kt
  app/src/main/java/com/runnect/runnect/data/service/ReverseGeocodingService.kt
  app/src/main/java/com/runnect/runnect/data/source/remote/RemoteReverseGeocodingDataSource.kt
  app/src/main/java/com/runnect/runnect/di/RepositoryModule.kt
  app/src/main/java/com/runnect/runnect/di/ServiceModule.kt
  app/src/main/java/com/runnect/runnect/domain/ReverseGeocodingRepository.kt
  app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/draw/DrawViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/search/SearchActivity.kt
  app/src/main/java/com/runnect/runnect/util/extension/ContextExt.kt
  app/src/main/res/drawable/draw_custom_departure_tv_guide.xml
  app/src/main/res/layout/activity_draw.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/bottomsheet_require_course_name.xml
  app/src/main/res/layout/custom_info_window.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 우남 🐼, FEAT ✨

#256 [MOD] 러닝 페이지 / 마커 리소스 수정
  app/src/main/java/com/runnect/runnect/data/service/ReverseGeocodingService.kt
  app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt
Labels: 우남 🐼, UI 🎨, MOD ☁

#261 [UI] 마이페이지 / UI 수정 사항 반영
  app/src/main/java/com/runnect/runnect/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/editname/MyPageEditNameActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/reward/MyRewardActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/reward/MyRewardViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/setting/MySettingFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadActivity.kt
  app/src/main/res/drawable/ic_mypage_nickname_edit.xml
  app/src/main/res/drawable/my_page_edit_border.xml
  app/src/main/res/drawable/my_page_nickname_edit_border.xml
  app/src/main/res/drawable/progressbar_custom.xml
  app/src/main/res/layout/activity_my_page_edit_name.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/colors.xml
Labels: 하은 🐰, UI 🎨, MOD ☁

#263 [CHORE] 파일 추가 / 누락된 파일 release 폴더에 추가
  app/build.gradle
  app/src/debug/res/drawable/draw_require_course_name_border.xml
  app/src/main/res/layout/bottomsheet_require_course_name.xml
  app/src/main/res/values/strings.xml
  app/src/release/res/drawable/draw_require_course_name_border.xml
  app/src/release/res/drawable/ic_current_location.xml
  app/src/release/res/drawable/ic_custom_location.xml
  app/src/release/res/drawable/ic_drag.xml
  app/src/release/res/drawable/ic_info_window.xml
Labels: 우남 🐼, ADD ➕, CHORE 🛠

#269 [REFACTOR] 마이페이지 러닝기록 상세페이지 / 액티비티의 전역변수를 뷰모델로 이전
  app/src/main/java/com/runnect/runnect/presentation/mypage/history/detail/MyHistoryDetailActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/history/detail/MyHistoryDetailViewModel.kt
Labels: 하은 🐰, REFACTOR 🧹
