Repository Runnect/Runnect-Android, pull requests merged in 2023-11, with the labels that each got.

#271 [CHORE] 마이페이지 러닝기록 / 제목 수정 시, 키보드 완료 버튼 누르면 바로 수정되도록 변경
  app/src/main/java/com/runnect/runnect/data/service/UserService.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/history/detail/MyHistoryDetailActivity.kt
  app/src/main/res/layout/activity_my_history_detail.xml
Labels: 하은 🐰, CHORE 🛠

#272 [REFACTOR] 출발지 모드 세팅 / Enum Class 활용
  app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
  app/src/main/java/com/runnect/runnect/util/DepartureSetMode.kt
Labels: 우남 🐼, REFACTOR 🧹

#279 [FEAT] 코스 그리기 / 코스 제목 입력 후 키보드 내리기
  app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
Labels: 우남 🐼, FEAT ✨

#277 [MOD] 상세페이지 / 보관함으로 뒤로가기 및 코스 삭제 시 애니메이션 통일
  app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
  app/src/main/java/com/runnect/runnect/util/extension/ActivityExt.kt
Labels: 우남 🐼, MOD ☁

#278 [FIX] 러닝 기록 / 삭제 버튼 활성화 오류
  app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryViewModel.kt
  app/src/main/res/layout/activity_my_history.xml
Labels: 우남 🐼, FIX 💥
