Repository Runnect/Runnect-Android, pull requests merged in 2023-12, with the labels that each got.

#288 [FIX] setOnlyAlertOnce 추가를 통한 소리/진동 제한
  app/src/main/java/com/runnect/runnect/presentation/run/RunActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/run/TimerService.kt
Labels: 우남 🐼, FIX 💥

#290 [ADD] 개발자 모드 추가
  .github/workflows/CI.yml
  app/build.gradle
  app/src/debug/AndroidManifest.xml
  app/src/debug/java/com/runnect/runnect/developer/RunnectDeveloperActivity.kt
  app/src/debug/res/xml/preferences_developer_menu.xml
  app/src/main/java/com/runnect/runnect/application/ApiMode.kt
  app/src/main/java/com/runnect/runnect/application/ApplicationClass.kt
  app/src/main/java/com/runnect/runnect/data/service/TokenAuthenticator.kt
  app/src/main/java/com/runnect/runnect/di/RetrofitModule.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/setting/MySettingFragment.kt
  app/src/main/res/layout/activity_runnect_developer.xml
  app/src/main/res/layout/fragment_my_setting.xml
  app/src/main/res/values/strings.xml
Labels: ADD ➕, 동현 🐨

#302 [UI] 코스 발견 / 상세페이지 프로필 조회 화면 구현
  app/src/main/java/com/runnect/runnect/data/dto/ProfileCourseData.kt
  app/src/main/java/com/runnect/runnect/presentation/profile/ProfileActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/profile/ProfileCourseAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/profile/ProfileViewModel.kt
  app/src/main/res/layout/activity_course_detail.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/item_profile_course.xml
  app/src/main/res/values/strings.xml
Labels: UI 🎨, 혜선 🐱
