Repository Runnect/Runnect-Android, pull requests merged in 2024-01, with the labels that each got.

#301 [FEAT] 코스 발견 / 중첩 리사이클러뷰에서 추천 코스 무한 스크롤
  app/src/main/java/com/runnect/runnect/data/dto/response/ResponseGetDiscoverRecommend.kt
  app/src/main/java/com/runnect/runnect/data/repository/CourseRepositoryImpl.kt
  app/src/main/java/com/runnect/runnect/domain/entity/DiscoverMultiViewItem.kt
  app/src/main/java/com/runnect/runnect/domain/entity/RecommendCoursePagingData.kt
  app/src/main/java/com/runnect/runnect/domain/repository/CourseRepository.kt
  app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverMultiViewAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverMultiViewHolder.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewHolder.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewHolderFactory.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewType.kt
  app/src/main/java/com/runnect/runnect/presentation/login/LoginActivity.kt
  app/src/main/java/com/runnect/runnect/util/custom/deco/DiscoverMarathonItemDecoration.kt
  app/src/main/java/com/runnect/runnect/util/custom/deco/DiscoverRecommendItemDecoration.kt
  app/src/main/java/com/runnect/runnect/util/extension/ContextExt.kt
  app/src/main/java/com/runnect/runnect/util/extension/ViewExt.kt
  app/src/main/res/layout/item_discover_marathon.xml
  app/src/main/res/layout/item_discover_multiview_recommend.xml
  app/src/main/res/layout/item_discover_recommend.xml
  app/src/main/res/values/strings.xml
Labels: 하은 🐰, FEAT ✨, MOD ☁

#304 [FIX] 위치 권한 거부 시 비정상 종료 해결 및 위치 권한 팝업 플로우 변경
  app/src/main/java/com/runnect/runnect/presentation/coursemain/CourseMainFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/mydrawdetail/MyDrawDetailActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/search/SearchActivity.kt
  app/src/main/java/com/runnect/runnect/util/extension/PermissionExt.kt
  app/src/main/res/values/strings.xml
Labels: FIX 💥, 혜선 🐱

#305 [FEAT] 코스 발견 / 상세페이지 타 유저 프로필 조회
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/runnect/runnect/data/dto/ProfileCourseData.kt
  app/src/main/java/com/runnect/runnect/data/dto/response/ResponseGetCourseDetail.kt
  app/src/main/java/com/runnect/runnect/data/dto/response/ResponseGetUserProfile.kt
  app/src/main/java/com/runnect/runnect/data/dto/response/ResponsePostScrap.kt
  app/src/main/java/com/runnect/runnect/data/repository/CourseRepositoryImpl.kt
  app/src/main/java/com/runnect/runnect/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/runnect/runnect/data/service/CourseService.kt
  app/src/main/java/com/runnect/runnect/data/service/UserService.kt
  app/src/main/java/com/runnect/runnect/data/source/remote/RemoteCourseDataSource.kt
  app/src/main/java/com/runnect/runnect/data/source/remote/RemoteUserDataSource.kt
  app/src/main/java/com/runnect/runnect/domain/entity/CourseDetail.kt
  app/src/main/java/com/runnect/runnect/domain/entity/UserProfile.kt
  app/src/main/java/com/runnect/runnect/domain/repository/CourseRepository.kt
  app/src/main/java/com/runnect/runnect/domain/repository/UserRepository.kt
  app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/profile/ProfileActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/profile/ProfileCourseAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/profile/ProfileViewModel.kt
  app/src/main/java/com/runnect/runnect/util/binding/BindingAdapter.kt
  app/src/main/res/layout/activity_course_detail.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/item_profile_course.xml
Labels: FEAT ✨, 혜선 🐱

#309 [FIX] 코스 발견 / 마라톤, 추천 코스 조회 로직 수정
  app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverMarathonAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverRecommendAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewHolder.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewHolderFactory.kt
Labels: 하은 🐰, FIX 💥
