Repository Runnect/Runnect-Android, pull requests merged in 2024-02, with the labels that each got.

#311 [FEAT] 코스 생성 api 수정 사항 반영 및 버그 대응
  app/src/main/java/com/runnect/runnect/data/dto/response/ResponsePostMyDrawCourse.kt
  app/src/main/java/com/runnect/runnect/data/repository/CourseRepositoryImpl.kt
  app/src/main/java/com/runnect/runnect/data/service/CourseService.kt
  app/src/main/java/com/runnect/runnect/data/source/remote/RemoteCourseDataSource.kt
  app/src/main/java/com/runnect/runnect/domain/repository/CourseRepository.kt
  app/src/main/java/com/runnect/runnect/presentation/draw/DrawActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/draw/DrawViewModel.kt
Labels: 우남 🐼, FEAT ✨, FIX 💥

#318 [FEAT] 코스 발견 / 추천 코스 정렬 기능
  app/src/main/java/com/runnect/runnect/data/repository/CourseRepositoryImpl.kt
  app/src/main/java/com/runnect/runnect/data/service/CourseService.kt
  app/src/main/java/com/runnect/runnect/data/source/remote/RemoteCourseDataSource.kt
  app/src/main/java/com/runnect/runnect/domain/repository/CourseRepository.kt
  app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverMarathonAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverRecommendAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewHolder.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewHolderFactory.kt
  app/src/main/java/com/runnect/runnect/util/extension/ContextExt.kt
Labels: 하은 🐰, FEAT ✨

#316 [ADD] 마이페이지, 보관함, 발견 / 이벤트 태깅
  app/src/main/java/com/runnect/runnect/application/ApplicationClass.kt
  app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/search/DiscoverSearchActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/upload/DiscoverUploadActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/history/MyHistoryActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/setting/MySettingFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/setting/accountinfo/MySettingAccountInfoFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/profile/ProfileActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/storage/StorageMainFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/storage/StorageMyDrawFragment.kt
  app/src/main/java/com/runnect/runnect/util/analytics/Analytics.kt
  app/src/main/java/com/runnect/runnect/util/analytics/EventName.kt
Labels: ADD ➕, 혜선 🐱

#317 [ADD] CommonToolbarLayout(BaseToolbar) 추가
  app/src/main/java/com/runnect/runnect/util/custom/popup/RunnectPopupMenu.kt
  app/src/main/java/com/runnect/runnect/util/custom/toolbar/BaseToolbarMenu.kt
  app/src/main/java/com/runnect/runnect/util/custom/toolbar/CommonToolbarLayout.kt
  app/src/main/java/com/runnect/runnect/util/custom/toolbar/ToolbarMenu.kt
  app/src/main/java/com/runnect/runnect/util/extension/ViewExt.kt
  app/src/main/res/layout/layout_common_toolbar.xml
Labels: ADD ➕, 동현 🐨

#320 [FIX] 서버 통신에 성공한 경우에만 스크랩 갱신시키도록 변경
  app/src/main/java/com/runnect/runnect/data/dto/response/ResponseGetMyScrapCourse.kt
  app/src/main/java/com/runnect/runnect/data/repository/StorageRepositoryImpl.kt
  app/src/main/java/com/runnect/runnect/data/service/CourseService.kt
  app/src/main/java/com/runnect/runnect/data/source/remote/RemoteStorageDataSource.kt
  app/src/main/java/com/runnect/runnect/domain/entity/MyScrapCourse.kt
  app/src/main/java/com/runnect/runnect/domain/repository/StorageRepository.kt
  app/src/main/java/com/runnect/runnect/presentation/MainActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverMarathonAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverRecommendAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/search/DiscoverSearchActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/search/DiscoverSearchViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/search/adapter/DiscoverSearchAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/storage/StorageMyDrawFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/storage/StorageScrapFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/storage/StorageViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/storage/adapter/StorageScrapAdapter.kt
  app/src/main/java/com/runnect/runnect/util/callback/listener/OnScrapItemClick.kt
  app/src/main/java/com/runnect/runnect/util/extension/ContextExt.kt
  app/src/main/res/layout/activity_course_detail.xml
  app/src/main/res/layout/fragment_storage_scrap.xml
  app/src/main/res/layout/item_storage_scrap.xml
Labels: 하은 🐰, FIX 💥

#323 [FIX] 코스 발견 / 내가 그린 코스 업로드
  app/src/main/java/com/runnect/runnect/data/dto/CourseLoadInfoDTO.kt
  app/src/main/java/com/runnect/runnect/data/dto/response/ResponseGetDiscoverPick.kt
  app/src/main/java/com/runnect/runnect/data/dto/response/ResponseGetDiscoverUploadCourse.kt
  app/src/main/java/com/runnect/runnect/data/repository/CourseRepositoryImpl.kt
  app/src/main/java/com/runnect/runnect/data/service/CourseService.kt
  app/src/main/java/com/runnect/runnect/domain/entity/DiscoverUploadCourse.kt
  app/src/main/java/com/runnect/runnect/domain/repository/CourseRepository.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/pick/DiscoverPickActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/pick/DiscoverPickViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/pick/adapter/DiscoverPickAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/upload/DiscoverUploadActivity.kt
  app/src/main/java/com/runnect/runnect/util/callback/DeleteMyDrawCourse.kt
  app/src/main/java/com/runnect/runnect/util/callback/listener/OnBannerItemClick.kt
  app/src/main/java/com/runnect/runnect/util/callback/listener/OnCourseUploadItemClick.kt
  app/src/main/java/com/runnect/runnect/util/callback/listener/OnRecommendItemClick.kt
  app/src/main/java/com/runnect/runnect/util/extension/ResponseExt.kt
  app/src/main/res/layout/activity_discover_pick.xml
  app/src/main/res/layout/activity_discover_upload.xml
  app/src/main/res/layout/item_discover_pick.xml
  app/src/main/res/values/strings.xml
Labels: 하은 🐰, FIX 💥, REFACTOR 🧹

#325 [FIX] 코스 발견 / 스크랩 함수의 로직 수정
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverMarathonAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/DiscoverRecommendAdapter.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/adapter/multiview/DiscoverMultiViewAdapter.kt
Labels: 하은 🐰, FIX 💥

#328 [FIX] 마이페이지 / 러닝 기록 api responseDTO 수정
  app/src/main/java/com/runnect/runnect/data/dto/response/ResponseGetMyHistory.kt
Labels: 우남 🐼, FIX 💥

#332 [FIX] 마이페이지 / 업로드한 코스 재생성 문제 해결
  app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
Labels: FIX 💥, 혜선 🐱

#326 [FEAT] 코스 상세 페이지 / Firebase 동적 링크로 코스 공유 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/runnect/runnect/data/service/TokenAuthenticator.kt
  app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
Labels: 우남 🐼, FEAT ✨

#333 [FIX] 코스 발견 / 내가 그린 코스 업로드 시, 단일 선택만 가능하도록 변경
  app/src/main/java/com/runnect/runnect/presentation/discover/pick/DiscoverPickActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/pick/DiscoverPickViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/pick/adapter/DiscoverPickAdapter.kt
Labels: 하은 🐰, FIX 💥

#334 [FIX] 코스 상세페이지 / 이전 화면으로 돌아갔을 때 변경사항 바로 반영되도록
  app/src/main/java/com/runnect/runnect/data/dto/UserUploadCourseDTO.kt
  app/src/main/java/com/runnect/runnect/presentation/detail/CourseDetailActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/DiscoverFragment.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/model/EditableDiscoverCourse.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/search/DiscoverSearchActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/discover/upload/DiscoverUploadActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadActivity.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/upload/MyUploadViewModel.kt
  app/src/main/java/com/runnect/runnect/presentation/mypage/upload/adapter/MyUploadAdapter.kt
Labels: 하은 🐰, FIX 💥
